services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jobs.groovy:/var/jenkins_home/jobs.groovy:ro
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml:ro
    group_add:
      - "998"
    user: root
    restart: always
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home: