services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # Add a bind mount for the configuration
      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
    networks:
      - jenkins-network
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home: