jenkins:
  systemMessage: "Jenkins configured using JCasC - Script approval disabled for trusted environment"
  noUsageStatistics: true
  primaryView:
    all:
      name: "all"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "dbjwhs"
          password: "jenkins"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  remotingSecurity:
    enabled: true

security:
  # Disable script approval for trusted environment
  scriptApproval:
    # Disable script approval entirely for this protected machine
    approvedSignatures:
      # Basic Groovy/Java methods
      - "method java.lang.String toLowerCase"
      - "method java.lang.String join java.lang.CharSequence"
      - "method java.util.List add java.lang.Object"
      - "staticMethod java.lang.System getenv java.lang.String"
      
      # Jenkins Pipeline DSL methods
      - "method hudson.model.Run getEnvironment hudson.model.TaskListener"
      - "method jenkins.model.Jenkins getItemByFullName java.lang.String"
      
      # File operations (commonly needed)
      - "new java.io.File java.lang.String"
      - "method java.io.File exists"
      - "method java.io.File isFile"
      - "method java.io.File isDirectory"
      - "method java.io.File getName"
      - "method java.io.File getPath"
      - "method java.io.File getAbsolutePath"
      
      # String operations
      - "method java.lang.String contains java.lang.CharSequence"
      - "method java.lang.String startsWith java.lang.String"
      - "method java.lang.String endsWith java.lang.String"
      - "method java.lang.String replace java.lang.CharSequence java.lang.CharSequence"
      - "method java.lang.String split java.lang.String"
      - "method java.lang.String trim"
      - "method java.lang.String substring int"
      - "method java.lang.String substring int int"
      
      # Collection operations
      - "method java.util.Collection size"
      - "method java.util.Collection isEmpty"
      - "method java.util.List get int"
      - "method java.util.Map get java.lang.Object"
      - "method java.util.Map put java.lang.Object java.lang.Object"
      - "method java.util.Map containsKey java.lang.Object"
      
      # Pipeline specific approvals for our jobs
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods any java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods collect java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods each java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods findAll java.lang.Object groovy.lang.Closure"
      
      # Job DSL specific signatures (prevents most DSL approval issues)
      - "new groovy.util.ConfigSlurper"
      - "staticMethod jenkins.model.Jenkins getInstance"
      - "method jenkins.model.Jenkins getItem java.lang.String"
      - "method hudson.model.ItemGroup getItem java.lang.String"
      - "staticMethod hudson.model.Hudson getInstance"
      - "method hudson.model.Item getName"
      - "method hudson.model.Item getFullName"
      - "new java.util.HashMap"
      - "new java.util.ArrayList"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map$Entry"
      - "method groovy.util.ConfigObject getProperty java.lang.String"
      
      # Additional DSL operations
      - "method java.lang.Class forName java.lang.String"
      - "staticMethod java.lang.Class forName java.lang.String"
      - "method java.lang.Object getClass"
      - "new java.lang.RuntimeException java.lang.String"
      - "method java.lang.Throwable printStackTrace"
      - "staticMethod groovy.lang.GroovySystem getVersion"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "mac-mini-ssh"
              username: "dbjones"
              description: "SSH key for Mac mini M2 agent"
              privateKeySource:
                directEntry:
                  privateKey: ${MAC_MINI_SSH_KEY}
          - string:
              scope: GLOBAL
              id: "anthropic-api-key"
              description: "Anthropic API key for Claude integration"
              secret: ${ANTHROPIC_API_KEY}

jenkins:
  nodes:
    - permanent:
        name: "mac-mini-m2"
        labelString: "macos m2 arm64 native"
        mode: NORMAL
        numExecutors: 4
        remoteFS: "/Users/dbjones/jenkins-agent"
        launcher:
          ssh:
            host: "host.docker.internal"
            port: 22
            credentialsId: "mac-mini-ssh"
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
        nodeProperties:
          - envVars:
              env:
                - key: "HOMEBREW_PREFIX"
                  value: "/opt/homebrew"
                - key: "PATH"
                  value: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
                - key: "CMAKE_PREFIX_PATH"
                  value: "/opt/homebrew"
        retentionStrategy:
          always: {}

jobs:
  - file: /var/jenkins_home/jobs.groovy

appearance:
  themeManager:
    disableUserThemes: false
    theme: "darkSystem"

unclassified:
  # Disable script security for trusted environment
  scriptSecurity:
    # Turn off sandbox for all pipeline scripts
    enableSandbox: false
  
  # Global Pipeline Libraries configuration
  globalLibraries:
    libraries: []
