jenkins:
  systemMessage: "Jenkins configured using JCasC"
  noUsageStatistics: true
  primaryView:
    all:
      name: "all"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "dbjwhs"
          password: "jenkins"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  remotingSecurity:
    enabled: true

security:
  # Option 1: Disable sandbox for Job DSL scripts (recommended for development)
  # This allows Job DSL scripts to run without script approval
  jobDsl:
    scriptSecurity:
      sandbox: false
      
  scriptApproval:
    approvedSignatures:
      # Basic Groovy/Java methods
      - "method java.lang.String toLowerCase"
      - "method java.lang.String join java.lang.CharSequence"
      - "method java.util.List add java.lang.Object"
      - "staticMethod java.lang.System getenv java.lang.String"
      
      # Jenkins Pipeline DSL methods
      - "method hudson.model.Run getEnvironment hudson.model.TaskListener"
      - "method jenkins.model.Jenkins getItemByFullName java.lang.String"
      
      # File operations (commonly needed)
      - "new java.io.File java.lang.String"
      - "method java.io.File exists"
      - "method java.io.File isFile"
      - "method java.io.File isDirectory"
      - "method java.io.File getName"
      - "method java.io.File getPath"
      - "method java.io.File getAbsolutePath"
      
      # String operations
      - "method java.lang.String contains java.lang.CharSequence"
      - "method java.lang.String startsWith java.lang.String"
      - "method java.lang.String endsWith java.lang.String"
      - "method java.lang.String replace java.lang.CharSequence java.lang.CharSequence"
      - "method java.lang.String split java.lang.String"
      - "method java.lang.String trim"
      - "method java.lang.String substring int"
      - "method java.lang.String substring int int"
      
      # Collection operations
      - "method java.util.Collection size"
      - "method java.util.Collection isEmpty"
      - "method java.util.List get int"
      - "method java.util.Map get java.lang.Object"
      - "method java.util.Map put java.lang.Object java.lang.Object"
      - "method java.util.Map containsKey java.lang.Object"
      
      # Pipeline specific approvals for our jobs
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods any java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods collect java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods each java.lang.Object groovy.lang.Closure"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods findAll java.lang.Object groovy.lang.Closure"
      
      # Job DSL specific signatures (prevents most DSL approval issues)
      - "new groovy.util.ConfigSlurper"
      - "staticMethod jenkins.model.Jenkins getInstance"
      - "method jenkins.model.Jenkins getItem java.lang.String"
      - "method hudson.model.ItemGroup getItem java.lang.String"
      - "staticMethod hudson.model.Hudson getInstance"
      - "method hudson.model.Item getName"
      - "method hudson.model.Item getFullName"
      - "new java.util.HashMap"
      - "new java.util.ArrayList"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map$Entry"
      - "method groovy.util.ConfigObject getProperty java.lang.String"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"

jobs:
  - file: /var/jenkins_home/jobs.groovy
