jenkins:
  systemMessage: "Jenkins configured using JCasC"
  noUsageStatistics: true
  primaryView:
    all:
      name: "all"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "dbjwhs"
          password: "jenkins"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"

jobs:
  - file: /var/jenkins_home/jobs.groovy
