jenkins:
  systemMessage: "Jenkins configured using JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "dbjwhs"
          password: "jenkins"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  remotingSecurity:
    enabled: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-creds"

jobs:
  - script: >
      pipelineJob('python-hello-world') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/dbjwhs/jenkins')
                }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }